version: '2'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    networks:
      - nodeapp

  mysql:
    image: mysql
    networks:
      - nodeapp

networks:
  nodeapp:
    driver: bridge