version: '2'

services:
  web:
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/src
    networks:
      - nodeapp
    links:
      - db

  db:
    image: mysql
    networks:
      - nodeapp
    volumes:
      - .:/src/db
    environment:
      MYSQL_ROOT_PASSWORD: "root"  
      MYSQL_DATABASE: "bandstalkr"  
      MYSQL_USER: "root"  
      MYSQL_PASSWORD: "root"

networks:
  nodeapp:
    driver: bridge