version: '2'

services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    networks:
      - nodeapp
    links:
      - mysql:db

  mysql:
    image: mysql
    networks:
      - nodeapp
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_USER: root
      - MYSQL_DATABASE: bandstalkr
      - MYSQL_PASSWORD: root

networks:
  nodeapp:
    driver: bridge