version: '2'

services:
  web:
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    networks:
      - nodeapp
    links:
      - db

  db:
    image: mysql
    networks:
      - nodeapp
    ports:
      - "1337:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bandstalkr 
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    volumes:
      - ./data-volume:/var/lib/mysql

networks:
  nodeapp:
    driver: bridge